# Example xrp-ledger.toml file. These contents should not be considered
# authoritative for any real entity or business.
# Note: all fields and all sections are optional.

[METADATA]
modified = 2019-01-22T00:00:00.000Z
expires = 2019-03-01T00:00:00.000Z


[[ACCOUNTS]]
address = "rhuMHXnxGhGqJiHDBbwCqFb5KMAaGkwJeK"
desc = "Ripple-owned address for XDT"
# Note: This doesn't prove ownership of an account unless the
#   "Domain" field of the account in the XRP Ledger matches the
#   domain this file was served from.

[[SERVERS]]
json_rpc = "https://xrplcluster.com/"
ws = "wss://xrplcluster.com/"
peer = "wss://xrpl.ws/"
desc = "General purpose server cluster"


[[PRINCIPALS]]
name = "Jeremy Cody" # Primary spec author
email = "jeremy@xdtxrp.org" # Not my real email address
social_1 = "https://twitter.com/XDT_XRPL" # Social media username/handle as an alternative way to connect

[[CURRENCIES]]
code = "XDT"
issuer = "rhuMHXnxGhGqJiHDBbwCqFb5KMAaGkwJeK"
network = "mainnet"
display_decimals = 4
symbol = "https://github.com/jremmyy/website/blob/main/IconOnly_Transparent.png" # In practical situations, it may be unwise to use emoji

# End of file
